### ISSUE TITLE
崩溃

### ISSUE THREAD

**Issue by HeroBarry** [nuhkoca/NewsApp-MVVM-AAC-Room-DataBinding-RxJava2-Retrofit2-Glide4#2]
第一次启动会崩溃

**Comment by nuhkoca** [comment]
@HeroBarry what is the error output? I have never worked on this project for years :)

**Comment by HeroBarry** [comment]
我已经改好（by VPN ），我是中国这边的开发者


并已经改成支持 AndroidX&nbsp;


学到很多知识[主要为了学习room更好的用法 :) ]


谢谢

**Comment by nuhkoca** [comment]
You mean, is it working well? Thanks for your interest in the project :)

**Comment by HeroBarry** [comment]
是的，暂时保留了newsApi接口相关内容，已经在对它进行改造，在实验我的一些新的想法。

**Comment by nuhkoca** [comment]
Good to hear! Then I am closing the issue :)
